# Deployment to AWS S3 + CloudFront
language: node_js
node_js:
  - 10
dist: trusty

cache:
  directories:
    - node_modules

install:
  # Install Vue.js and Webpack Install
  - npm install -g @vue/cli
  # Install Travis CI CloudFront Invalidation Tool
  - npm install -g travis-ci-cloudfront-invalidation
  # Install NPM Dependencies
  - npm install --loglevel warn

script:
  - npm run build

deploy:
  - provider: s3
    skip_cleanup: true
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: ap-southeast-2
    bucket: archi-front
    local_dir: dist

after_deploy:
  - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY -s $AWS_SECRET_KEY -c $AWS_CLOUDFRONT_DIST_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST
